en:
  errors:
    messages:
      record_not_found: "We can not find %{record_name}"
